name: "Sub-issue"
description: "Sub-issue no formato [SI] - Objetivo"
projects: ["CLT-Devops/3"]
type: "Task"
body:
  - type: dropdown
    id: label
    attributes:
      label: Label
      description: Label obrigatoria para classificacao.
      options:
        - DB
        - AI
        - Code
        - Server
        - Domain
        - Story
        - API
        - Webhook
        - AWS
        - ETL
        - Docker
        - CI/CD
        - Log
        - QA
        - Sec
        - UI/UX
        - Layout
        - Component
    validations:
      required: true

  - type: textarea
    id: description_text
    attributes:
      label: Descricao
      placeholder: "Descreva resumidamente a demanda..."
    validations:
      required: true
